In [143]:
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

In [ ]:
df_titanic = pd.read_csv('../../datasets/structured/titanic.csv')
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [145]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [146]:
df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [147]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [148]:
df_titanic.drop(["PassengerId", "Name", "Ticket", "Cabin","Fare","Parch"], axis=1, inplace=True, errors='ignore')
df_titanic = df_titanic.dropna(subset=['Embarked'])
mean_age = df_titanic['Age'].mean()
df_titanic['Age'].fillna(mean_age, inplace=True)
df_titanic.columns

/tmp/ipython-input-321590277.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic['Age'].fillna(mean_age, inplace=True)

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Embarked'], dtype='object')

In [149]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    object
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Embarked  889 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 48.6+ KB

In [150]:
# แปลงข้อมูลข้อความเป็นตัวเลข
df_titanic["Sex"] = df_titanic["Sex"].map({"male": 0, "female": 1})

if "Embarked" in df_titanic.columns:
    df_titanic["Embarked"] = df_titanic["Embarked"].map({"S": 0, "C": 1, "Q": 2})

In [151]:
df_titanic.fillna(df_titanic.median(numeric_only=True), inplace=True)

In [152]:
y = df_titanic["Survived"].values
X = df_titanic.drop(["Survived"], axis=1)

In [153]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    stratify=y,
    random_state=9
)

# 5️⃣ สร้างและเทรนโมเดล Naive Bayes
clf_titanic = GaussianNB()
clf_titanic.fit(X_train, y_train)

GaussianNB()

In [154]:
df_titanic_predict = X_test.copy()
df_titanic_predict['predicted'] = clf_titanic.predict(X_test)
df_titanic_predict['actual'] = y_test

target_names = {0: 'Not Survived', 1: 'Survived'}
df_titanic_predict['actual'] = df_titanic_predict['actual'].map(target_names)
df_titanic_predict['predicted'] = df_titanic_predict['predicted'].map(target_names)

df_titanic_predict.head(10)

     Pclass  Sex        Age  SibSp  Embarked     predicted        actual
800       2    0  34.000000      0         0  Not Survived  Not Survived
512       1    0  36.000000      0         0  Not Survived      Survived
645       1    0  48.000000      1         1  Not Survived      Survived
37        3    0  21.000000      0         0  Not Survived  Not Survived
568       3    0  29.642093      0         1  Not Survived  Not Survived
142       3    1  24.000000      1         0      Survived      Survived
814       3    0  30.500000      0         0  Not Survived  Not Survived
395       3    0  22.000000      0         0  Not Survived  Not Survived
377       1    0  27.000000      0         1      Survived  Not Survived
21        2    0  34.000000      0         0  Not Survived      Survived

In [155]:
from sklearn import metrics
print(metrics.classification_report(y_test, clf_titanic.predict(X_test)))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85       165
           1       0.77      0.71      0.74       102

    accuracy                           0.81       267
   macro avg       0.80      0.79      0.79       267
weighted avg       0.81      0.81      0.81       267

In [156]:
metrics.confusion_matrix(y_test, clf_titanic.predict(X_test))

array([[144,  21],
       [ 30,  72]])

In [157]:
clf_titanic.score(X_test, y_test)

0.8089887640449438

In [158]:
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

k = 3

# Initialize Stratified KFold cross-validation
kf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)

# Initialize empty lists to store predictions and ground truth for all folds
all_y_true = []
all_y_pred = []
accuracy_scores=[]
confusion_matrices=[]

# Loop through each fold
for train_index, test_index in kf.split(X,y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Create a decision tree classifier
    clf = GaussianNB()

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Calculate accuracy for this fold and store it
    accuracy = accuracy_score(y_test, y_pred)
    accuracy_scores.append(accuracy)

    # Calculate confusion matrix and store it
    confusion = confusion_matrix(y_test, y_pred)
    confusion_matrices.append(confusion)

    # Store ground truth and predictions for this fold
    all_y_true.extend(y_test)
    all_y_pred.extend(y_pred)


# Calculate mean and standard deviation of accuracy scores
mean_accuracy = np.mean(accuracy_scores)
std_accuracy = np.std(accuracy_scores)

# Print evaluation metrics summary
print(f"Mean Accuracy: {mean_accuracy:.2f}")
print(f"Standard Deviation of Accuracy: {std_accuracy:.2f}")

# Print average confusion matrix (you can also compute other statistics from it)
sum_confusion_matrix = np.sum(confusion_matrices, axis=0)
print("\n\nSum Confusion Matrix:")
print(sum_confusion_matrix)


# Generate a classification report for all folds and classes
report = classification_report(all_y_true, all_y_pred, target_names=['Not Survived','Survived'])

# Display the classification report
print("\n\nClassification Report - All Folds and Classes:")
print(report)

Mean Accuracy: 0.78
Standard Deviation of Accuracy: 0.03


Sum Confusion Matrix:
[[440 109]
 [ 89 251]]


Classification Report - All Folds and Classes:
              precision    recall  f1-score   support

Not Survived       0.83      0.80      0.82       549
    Survived       0.70      0.74      0.72       340

    accuracy                           0.78       889
   macro avg       0.76      0.77      0.77       889
weighted avg       0.78      0.78      0.78       889